[[journals]]
name = "IEEE Transactions on Mobile Computing (TMC)"

[[conferences]]
name = "IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)"

[[conferences]]
name = "International Conference on Autonomous Agents and Multiagent Systems (AAMAS)"

