[[academic]]
title = "一等奖学金"
organization = "广东工业大学"
period = "2024年9月 - 2025年9月"
detail = "前3%"

[[academic]]
title = "优秀学生干部"
organization = "广东工业大学"
period = "2024年9月 - 2025年9月"

[[academic]]
title = "先进个人"
organization = "广东工业大学"
period = "2023年9月 - 2024年9月"

[[competitions]]
title = "全国二等奖"
organization = "全国大学生智能汽车竞赛"
period = "2025年6月 - 2025年9月"
detail = "200余支队伍中位列全国前5%"

[[competitions]]
title = "华南赛区三等奖"
organization = "全国大学生智能汽车竞赛"
period = "2024年7月 - 2024年8月"

